// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: authgrpc.proto

package authgrpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthGRPC_ValidateToken_FullMethodName = "/authgrpc.AuthGRPC/ValidateToken"
)

// AuthGRPCClient is the client API for AuthGRPC service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AuthGRPCClient interface {
	ValidateToken(ctx context.Context, in *TokenString, opts ...grpc.CallOption) (*ValidateTokenResponse, error)
}

type authGRPCClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthGRPCClient(cc grpc.ClientConnInterface) AuthGRPCClient {
	return &authGRPCClient{cc}
}

func (c *authGRPCClient) ValidateToken(ctx context.Context, in *TokenString, opts ...grpc.CallOption) (*ValidateTokenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateTokenResponse)
	err := c.cc.Invoke(ctx, AuthGRPC_ValidateToken_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthGRPCServer is the server API for AuthGRPC service.
// All implementations must embed UnimplementedAuthGRPCServer
// for forward compatibility.
type AuthGRPCServer interface {
	ValidateToken(context.Context, *TokenString) (*ValidateTokenResponse, error)
	mustEmbedUnimplementedAuthGRPCServer()
}

// UnimplementedAuthGRPCServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthGRPCServer struct{}

func (UnimplementedAuthGRPCServer) ValidateToken(context.Context, *TokenString) (*ValidateTokenResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ValidateToken not implemented")
}
func (UnimplementedAuthGRPCServer) mustEmbedUnimplementedAuthGRPCServer() {}
func (UnimplementedAuthGRPCServer) testEmbeddedByValue()                  {}

// UnsafeAuthGRPCServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthGRPCServer will
// result in compilation errors.
type UnsafeAuthGRPCServer interface {
	mustEmbedUnimplementedAuthGRPCServer()
}

func RegisterAuthGRPCServer(s grpc.ServiceRegistrar, srv AuthGRPCServer) {
	// If the following call panics, it indicates UnimplementedAuthGRPCServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthGRPC_ServiceDesc, srv)
}

func _AuthGRPC_ValidateToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenString)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthGRPCServer).ValidateToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthGRPC_ValidateToken_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthGRPCServer).ValidateToken(ctx, req.(*TokenString))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthGRPC_ServiceDesc is the grpc.ServiceDesc for AuthGRPC service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthGRPC_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authgrpc.AuthGRPC",
	HandlerType: (*AuthGRPCServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateToken",
			Handler:    _AuthGRPC_ValidateToken_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "authgrpc.proto",
}
