// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: authgrpc.proto

package authgrpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenString struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenString) Reset() {
	*x = TokenString{}
	mi := &file_authgrpc_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenString) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenString) ProtoMessage() {}

func (x *TokenString) ProtoReflect() protoreflect.Message {
	mi := &file_authgrpc_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenString.ProtoReflect.Descriptor instead.
func (*TokenString) Descriptor() ([]byte, []int) {
	return file_authgrpc_proto_rawDescGZIP(), []int{0}
}

func (x *TokenString) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type ValidateTokenResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	IsValid       bool                   `protobuf:"varint,2,opt,name=isValid,proto3" json:"isValid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateTokenResponse) Reset() {
	*x = ValidateTokenResponse{}
	mi := &file_authgrpc_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateTokenResponse) ProtoMessage() {}

func (x *ValidateTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_authgrpc_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateTokenResponse.ProtoReflect.Descriptor instead.
func (*ValidateTokenResponse) Descriptor() ([]byte, []int) {
	return file_authgrpc_proto_rawDescGZIP(), []int{1}
}

func (x *ValidateTokenResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ValidateTokenResponse) GetIsValid() bool {
	if x != nil {
		return x.IsValid
	}
	return false
}

var File_authgrpc_proto protoreflect.FileDescriptor

const file_authgrpc_proto_rawDesc = "" +
	"\n" +
	"\x0eauthgrpc.proto\x12\bauthgrpc\"#\n" +
	"\vTokenString\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"I\n" +
	"\x15ValidateTokenResponse\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\aisValid\x18\x02 \x01(\bR\aisValid2U\n" +
	"\bAuthGRPC\x12I\n" +
	"\rValidateToken\x12\x15.authgrpc.TokenString\x1a\x1f.authgrpc.ValidateTokenResponse\"\x00B&Z$github.com/yourorg/authgrpc;authgrpcb\x06proto3"

var (
	file_authgrpc_proto_rawDescOnce sync.Once
	file_authgrpc_proto_rawDescData []byte
)

func file_authgrpc_proto_rawDescGZIP() []byte {
	file_authgrpc_proto_rawDescOnce.Do(func() {
		file_authgrpc_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_authgrpc_proto_rawDesc), len(file_authgrpc_proto_rawDesc)))
	})
	return file_authgrpc_proto_rawDescData
}

var file_authgrpc_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_authgrpc_proto_goTypes = []any{
	(*TokenString)(nil),           // 0: authgrpc.TokenString
	(*ValidateTokenResponse)(nil), // 1: authgrpc.ValidateTokenResponse
}
var file_authgrpc_proto_depIdxs = []int32{
	0, // 0: authgrpc.AuthGRPC.ValidateToken:input_type -> authgrpc.TokenString
	1, // 1: authgrpc.AuthGRPC.ValidateToken:output_type -> authgrpc.ValidateTokenResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_authgrpc_proto_init() }
func file_authgrpc_proto_init() {
	if File_authgrpc_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_authgrpc_proto_rawDesc), len(file_authgrpc_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_authgrpc_proto_goTypes,
		DependencyIndexes: file_authgrpc_proto_depIdxs,
		MessageInfos:      file_authgrpc_proto_msgTypes,
	}.Build()
	File_authgrpc_proto = out.File
	file_authgrpc_proto_goTypes = nil
	file_authgrpc_proto_depIdxs = nil
}
